title: "Antonio Velazquez"
email: jantonio.vema@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Base project for GitHub Pages new site
baseurl: "/" 
url: "https://antonio072.github.io/ 
twitter_username: AntonioVelaz72
github_username:  Antonio072

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
